spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:chalupas99@cluster0.6zxtl.mongodb.net/?retryWrites=true&w=majority
      repositories:
        type: AUTO
      database: mutant

#server:
#  port: 8080

logging:
  level:
    root: info
    org.springframework.integration: info
    org.springframework.data.mongodb: info

